name: PHP 8.0 Docker build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - name: prepare and build the image
      - uses: actions/checkout@v2
        - run: docker build -t tmtde/fpm-80 .
        - run: docker run -i --rm -d tmtde/fpm-80
        - run: docker ps | grep -q fpm-80
        - run: docker run -i tmtde/fpm-80 php -v | grep -E "^PHP\s8\.0"
        - run: docker run -i tmtde/fpm-80 composer --version
        - run: docker run -i tmtde/fpm-80 php -r 'print (iconv("utf-8", "ASCII//TRANSLIT", "ströng contäning ümlaöits"));'
